### ISSUE TITLE
Question in custom serialize?

### ISSUE THREAD

**Issue by pedia** [mrevutskyi/flask-restless-ng#2]
First:

I noticed in views.py `API.get` 
call `self.serialize` when `instid` provided
call `to_dict` without `instid`

How about calling `self.serialize` in these two routines?

Second:
How about custom serialize in this way:
```python
class Person(db.Model):
    id = db.Column(db.Integer, primary_key=True)
    name = db.Column(db.Unicode)

    @staticmethod
    def to_dict(inst):
        return dict(id=inst.id, name=inst.name)
```

And:
> Provided model must have an `id` attribute

This is too distressed. What's the benefit with `id`?

**Comment by mrevutskyi** [comment]
hi, could you please link the exact code you are describing? I can't find any usage of `to_dict`

**Comment by pedia** [comment]
My bad, this code was in tag 0.17.0

to_dict was in views.py [_paginated](https://github.com/mrevutskyi/flask-restless-ng/blob/0.17.0/flask_restless/views.py#L976)

self.serialize was in [get](https://github.com/mrevutskyi/flask-restless-ng/blob/0.17.0/flask_restless/views.py#L1258)

I think these code is refactored much changed since 1.0.0, ignored my question.
