### ISSUE TITLE
Can you plublish this to pypi?

### ISSUE THREAD

**Issue by reubano** [mrevutskyi/flask-restless-ng#21]
Then we can pip install it.

https://packaging.python.org/tutorials/packaging-projects/

**Comment by mrevutskyi** [comment]
but it is already on pypi https://pypi.org/project/Flask-Restless-NG/

**Comment by reubano** [comment]
Ah ok. It didn't have `pip install Flask-Restless-NG` in the readme so I assumed It wasn't published.

**Comment by mrevutskyi** [comment]
Good point, I'll update the readme

**Comment by reubano** [comment]
Cool, thanks!
