### ISSUE TITLE
FunctionAPI alternative?

### ISSUE THREAD

**Issue by mosheduminer** [mrevutskyi/flask-restless-ng#23]
It looks like the FunctionAPI class was removed. Is there an alternative?

By the way, thanks for your swift response on #22.

**Comment by mosheduminer** [comment]
Never mind, don't know what I was thinking.

**Comment by mosheduminer** [comment]
Hey, so I figured out what was going on the in the code I was porting. It was monkey patching FunctionAPI, which is used internally for function evaluation in the `APIManager`. However, I see that the 2.x release has removed function evaluation. Given that this library no longer supports function evaluation, what available alternative is there?

**Comment by mrevutskyi** [comment]
Somehow missed your response.
I guess it depends what were you using function evaluations for.
If to collect/aggregate data, then creating a simple Flask endpoint is what I usually do. That way you can also fine-tune your SQL queries (remove unnecessary fields, or joins, etc)

**Comment by mosheduminer** [comment]
Yeah, that's a good idea, and that may be what I'll do eventually. Unfortunately there's already a large number of consumers of the eval endpoints, and I'd have to take them all into account. For now I am using the original FunctionAPI code and adding it to the blueprints. I don't consider that a great long term option (as it might make version updates more difficult), so I'm considering what to do, including your suggestion 👍.

**Comment by mrevutskyi** [comment]
I see.
I've added it back in version 2.1.0 with a deprecation warning, and going to deprecate it for good in 3.x
