### ISSUE TITLE
Package should install all dependencies

### ISSUE THREAD

**Issue by gabrielfior** [mrevutskyi/flask-restless-ng#36]
Love this package! As a suggestion, would say that the package should recommend all dependencies (Flask-SQLAlchemy missing). If it also works without deps, please state so in the README.

**Comment by mrevutskyi** [comment]
Hi, sorry for the delayed response. 
The README currently says `using either SQLAlchemy or Flask-SQLAlchemy`. It does not say anywhere that it's a requirement. 
How do you think it should be phrased instead?
