### ISSUE TITLE
Integration w Prisma

### ISSUE THREAD

**Issue by reubano** [mrevutskyi/flask-restless-ng#39]
Just spitballing here, but it would be great if this could work with the [Prisma ORM](https://prisma-client-py.readthedocs.io/en/stable/). While I'm a huge fan of SQLAlchemy, Prisma integration would open the door to using the [Prisma Studio](https://www.prisma.io/studio) (and potentially [Supabase Studio](https://supabase.com/blog/supabase-studio)) admin interface. 

I'm sure this is out of scope for this project, but a pluggable ORM would be killer.

Edit. My inspiration for this issue is [A beginners guide to building a Flask API with Prisma](https://dev.to/mihaiandrei97/a-beginners-guide-to-building-a-flask-api-with-prisma-1g6i) which has a ton of [API routing boilerplate](https://dev.to/mihaiandrei97/a-beginners-guide-to-building-a-flask-api-with-prisma-1g6i#routes) that could be eliminated with the above idea.

**Comment by mrevutskyi** [comment]
Thank you for the suggestion.
I'm afraid that Prisma and SQLAlchemy use very different approaches, and SQLAlchemy is too tightly integrated in the flask-restless architecture. I like the idea of pluggable ORM/engines, and even played with it a little a while ago. But it would be easier to start a new project from scratch, than try to re-design this one, as it would break the existing API anyway.
Unfortunately I only have time to maintain the existing API and dependencies, and that is too big of a project

**Comment by reubano** [comment]
@mrevutskyi I figured as much. Can you point me in the right direction if I ever decide to take something like this on myself? What tips/suggestions do you have from your exploration?

**Comment by mrevutskyi** [comment]
Not sure I have actual practical tips, just general ideas that I was thinking :)
My plan was to develop two main interfaces:
1. For input/db access (e.g.  SQLAlchemy, Prisma, etc.)
2. For output/serialization (e.g JSON:API, other specifications)

Plus interfaces to customize search parameters
