### ISSUE TITLE
ImportError: cannot import name 'HYBRID_PROPERTY' from 'sqlalchemy.ext.hybrid'

### ISSUE THREAD

**Issue by samialfattani** [mrevutskyi/flask-restless-ng#40]
the following error just raised once the first import of flask_restless!!

`ImportError: cannot import name 'HYBRID_PROPERTY' from 'sqlalchemy.ext.hybrid'`

if have just used the snippet code that is listed in [Quickstart](https://flask-restless-ng.readthedocs.io/en/2.5.0/quickstart.html) page

any explanation?

**Comment by mrevutskyi** [comment]
What version of SQLAlchemy do you use?

**Comment by samialfattani** [comment]
it was `SQLAlchemy==2.0.5`

and then i updated it into the last version:
`last version SQLAlchemy==2.0.6`


but it didn't work in all cases
also i updated Flask, Flask-Sqlalchemy into the last version, but still same error is raising!

**Comment by mrevutskyi** [comment]
Thank you for the report and for the additional info. 
It has only been tested with SQLAlchemy 1.x
I was able to reproduce your issue with 2.0.6. Will try so post a fix soon-ish

**Comment by mrevutskyi** [comment]
I took a quick look and adding support for SQLAlchemy 2.0 would require some major changes and will break compatibility with 1.3-1.4, and will be added in flask-restless-ng 3.0. But that would take some time
For now I have restricted SQLAlchemy version to >=1.3,<2.0

**Comment by mrevutskyi** [comment]
Fixed in version 3.0.0
