### ISSUE TITLE
Merge with flask-restless

### ISSUE THREAD

**Issue by reubano** [mrevutskyi/flask-restless-ng#7]
Just curious, why don't you take over maintenance of the original @jfinkels flask-restless repo?

**Comment by mrevutskyi** [comment]
I reached out to @jfinkels and he suggested to create a fork. I guess he does not have to review PRs, and give away full control of the repo to some stranger (me) who might not know what is doing is not very reasonable :)

**Comment by reubano** [comment]
Gotcha. Hopefully he'll have time in the future to merge your work then. I remember reading something about a slew of changes for the unreleased v2. It may be worthwhile speaking to him again to find out what improvements he had in mind.
